/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spider;

public class App {


    public static void main(String[] args) {
        mafenetrex principale = new mafenetrex();
    }
}
